allprojects {
  apply plugin: 'java'
  
  
  // compiler options
  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }
  
  repositories { mavenCentral() }
  
  // gradle publish | publishToMavenLocal
  apply from: "$rootProject.projectDir/maven.gradle"
}


subprojects {
  apply plugin: 'eclipse'
  
  
  dependencies {
  
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
  
    // mocking framework
    testImplementation 'org.mockito:mockito-core:5.4.0'
    
    // logging
    testImplementation 'ch.qos.logback:logback-classic:1.4.4'
  }
  
  
  // The character encoding to be used when reading source files
  tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
  
  
  test {
    // Use JUnit Jupiter test framework
    useJUnitPlatform()
  
    // show standard out and standard error of the test JVM(s) on the console
    testLogging.showStandardStreams true
    
    ignoreFailures false
    
  }
  /*testing {
	  suites {
	    test {
	      // Use JUnit Jupiter test framework
	      useJUnitJupiter('5.10.1')
	    }
	  }
	}*/
  
}



apply plugin: 'java-library'
dependencies {
  implementation project(':jawn-core')
  implementation project(':jawn-server-undertow')
  implementation project(':jawn-jackson')
}

//apply from: 'uberjar.gradle'
