apply plugin: 'maven-publish'
apply plugin: 'signing'

// maven metadata
group = 'net.javapla.jawn'

// Collect the source
/*task sourcesJar(type: Jar) {
  from sourceSets.main.allSource
  archiveClassifier = 'sources'
}

// Generates the javadoc
task javadocJar(type: Jar) {
  from javadoc
  archiveClassifier = 'javadoc'
}*/

java {
  withJavadocJar()
  withSourcesJar()
}

ext.isReleaseVersion = !version.endsWith('SNAPSHOT')

publishing {
  publications {
    mavenJava(MavenPublication) {
      println artifactId
    
      from components.java
      
      /*artifact sourcesJar
      artifact javadocJar*/
      
      
      pom {
        name = "${project.group}:${rootProject.name}"
        description = 'jawn - A simple web framework in Java'
        url = 'https://github.com/MTDdk/jawn'
        
        licenses {
          license {
            name = 'GNU LGPL, Version 3.0'
            url = 'http://www.gnu.org/licenses/lgpl-3.0.txt'
          }
        }
        
        developers {
          developer {
            id = 'MTDdk'
            name = 'MTDdk'
            email = 'alvn@alvn.dk'
          }
        }
        
        issueManagement {
          system = 'Github Issues'
          url = 'https://github.com/MTDdk/jawn/issues'
        }
        
        scm {
          connection = 'scm:git://github.com/MTDdk/jawn.git'
          developerConnection = 'scm:git:git@github.com:MTDdk/jawn.git'
          url = 'https://github.com/MTDdk/jawn'
        }
      }
      
      
      repositories {
        maven {
          def releasesRepoUrl = "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"
          def snapshotsRepoUrl = "https://central.sonatype.com/repository/maven-snapshots/" 
          
          name = 'ossrh-staging-api'
          url = isReleaseVersion ? releasesRepoUrl : snapshotsRepoUrl
        
        
          gradle.taskGraph.whenReady { taskGraph ->
            if (taskGraph.hasTask(':generatePomFileForMavenJavaPublication') && !taskGraph.hasTask(':publishToMavenLocal')) {
            
              // only do any maven related if we have the needed properties available
              if (project.hasProperty('ossrhUsername') && project.hasProperty('ossrhPassword')) {
                credentials {
                  username = ossrhUsername
                  password = ossrhPassword
                }
              } else {
                throw new GradleException('You do not have your credentials stated')
              }
            }
          }

          
        }
      }
      
    }
  }
}



signing {
  required { isReleaseVersion }
  sign publishing.publications.mavenJava
}

javadoc {
  enabled = true
  
  if (JavaVersion.current().isJava9Compatible()) {
    options.addBooleanOption('html5', true)
  }
  
  failOnError = false
}
// <AUTH> can be generated with https://central.sonatype.com/api-doc
// or as described in https://central.sonatype.org/publish/publish-portal-api/#authentication-authorization
// $ printf "example_username:example_password" | base64
//curl -XPOST -i -H 'Authorization: Bearer <AUTH>' 'https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/net.javapla.jawn'
