/*
Copyright 2009-2014 Igor Polevoy

Licensed under the Apache License, Version 2.0 (the "License"); 
you may not use this file except in compliance with the License. 
You may obtain a copy of the License at 

http://www.apache.org/licenses/LICENSE-2.0 

Unless required by applicable law or agreed to in writing, software 
distributed under the License is distributed on an "AS IS" BASIS, 
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
See the License for the specific language governing permissions and 
limitations under the License. 
*/
package net.javapla.jawn.controller_filters;

import net.javapla.jawn.Context;

/**
 * This class is to be overridden by those filters that are to produce/override responses generated by controller.
 * One use case is to catch all exceptions and respond with a canned error (page), another is an authentication controller
 * that will redirect to a login page if user not logged in.  
 *
 * @author Igor Polevoy
 */
@Deprecated
public class HttpSupportFilter /*extends HttpSupport */implements ControllerFilter{
    public void before(Context context) {}

    public void after(Context context) {}

    /**
     *
     * @param e exception.
     */
    public void onException(Exception e) {}
}
